/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package hc.parallel.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class entry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"entry\",\"namespace\":\"parallel.avro\",\"fields\":[{\"name\":\"index\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int index;
  @Deprecated public float value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public entry() {}

  /**
   * All-args constructor.
   */
  public entry(java.lang.Integer index, java.lang.Float value) {
    this.index = index;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return index;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: index = (java.lang.Integer)value$; break;
    case 1: value = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'index' field.
   */
  public java.lang.Integer getIndex() {
    return index;
  }

  /**
   * Sets the value of the 'index' field.
   * @param value the value to set.
   */
  public void setIndex(java.lang.Integer value) {
    this.index = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.Float getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Float value) {
    this.value = value;
  }

  /** Creates a new entry RecordBuilder */
  public static hc.parallel.avro.entry.Builder newBuilder() {
    return new hc.parallel.avro.entry.Builder();
  }
  
  /** Creates a new entry RecordBuilder by copying an existing Builder */
  public static hc.parallel.avro.entry.Builder newBuilder(hc.parallel.avro.entry.Builder other) {
    return new hc.parallel.avro.entry.Builder(other);
  }
  
  /** Creates a new entry RecordBuilder by copying an existing entry instance */
  public static hc.parallel.avro.entry.Builder newBuilder(hc.parallel.avro.entry other) {
    return new hc.parallel.avro.entry.Builder(other);
  }
  
  /**
   * RecordBuilder for entry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<entry>
    implements org.apache.avro.data.RecordBuilder<entry> {

    private int index;
    private float value;

    /** Creates a new Builder */
    private Builder() {
      super(hc.parallel.avro.entry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(hc.parallel.avro.entry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing entry instance */
    private Builder(hc.parallel.avro.entry other) {
            super(hc.parallel.avro.entry.SCHEMA$);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'index' field */
    public java.lang.Integer getIndex() {
      return index;
    }
    
    /** Sets the value of the 'index' field */
    public hc.parallel.avro.entry.Builder setIndex(int value) {
      validate(fields()[0], value);
      this.index = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'index' field has been set */
    public boolean hasIndex() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'index' field */
    public hc.parallel.avro.entry.Builder clearIndex() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.lang.Float getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public hc.parallel.avro.entry.Builder setValue(float value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public hc.parallel.avro.entry.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public entry build() {
      try {
        entry record = new entry();
        record.index = fieldSetFlags()[0] ? this.index : (java.lang.Integer) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Float) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
